/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{vue,js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            // 软萌可爱色板 🌸
            colors: {
                'kawaii-pink': {
                    50: '#fff0f6',
                    100: '#ffe0ee',
                    200: '#ffc1dd',
                    300: '#ff92c2',
                    400: '#ff5ca7',
                    500: '#ff2d8c',
                    600: '#f7086e',
                    700: '#d10054',
                    800: '#ad0047',
                    900: '#8f003d',
                },
                'kawaii-purple': {
                    50: '#faf5ff',
                    100: '#f3e8ff',
                    200: '#e9d5ff',
                    300: '#d8b4fe',
                    400: '#c084fc',
                    500: '#a855f7',
                    600: '#9333ea',
                    700: '#7e22ce',
                    800: '#6b21a8',
                    900: '#581c87',
                },
                'kawaii-blue': {
                    50: '#f0f9ff',
                    100: '#e0f2fe',
                    200: '#bae6fd',
                    300: '#7dd3fc',
                    400: '#38bdf8',
                    500: '#0ea5e9',
                    600: '#0284c7',
                    700: '#0369a1',
                    800: '#075985',
                    900: '#0c4a6e',
                },
                'kawaii-cream': '#fffbf0',
                'kawaii-peach': '#ffd4d4',
                'kawaii-lavender': '#e6e6fa',
                'kawaii-mint': '#d4f5f0',
            },
            // 更大的圆角
            borderRadius: {
                'kawaii': '1.5rem',
                'kawaii-lg': '2rem',
                'kawaii-xl': '2.5rem',
            },
            // 柔和的阴影
            boxShadow: {
                'kawaii': '0 4px 20px rgba(255, 182, 193, 0.15)',
                'kawaii-lg': '0 10px 40px rgba(255, 182, 193, 0.25)',
                'kawaii-pink': '0 4px 20px rgba(255, 45, 140, 0.2)',
                'kawaii-purple': '0 4px 20px rgba(168, 85, 247, 0.2)',
            },
            // 可爱的字体
            fontFamily: {
                'kawaii': ['Quicksand', 'Noto Sans SC', 'sans-serif'],
                'cute': ['Comic Sans MS', 'Noto Sans SC', 'sans-serif'],
            },
        },
    },
    // v1.10.218: 显式 safelist 一些任意值类, 防止 Tailwind 扫描漏掉
    safelist: [
        'w-[50px]', 'h-[50px]', 'w-[30px]', 'h-[30px]', 'w-[44px]', 'h-[44px]',
        'w-[60px]', 'h-[60px]', 'w-[80px]', 'h-[80px]', 'w-[100px]', 'h-[100px]', 'w-[120px]', 'h-[120px]',
        'text-[9px]', 'text-[10px]', 'text-[11px]', 'text-[12px]', 'text-[13px]', 'text-[14px]',
        'text-[15px]', 'text-[16px]', 'text-[18px]', 'text-[20px]', 'text-[22px]', 'text-[24px]',
        'text-[26px]', 'text-[28px]', 'text-[30px]', 'text-[32px]', 'text-[34px]', 'text-[36px]',
        'text-[40px]', 'text-[44px]', 'text-[48px]', 'text-[56px]', 'text-[64px]',
        'bg-black/10', 'bg-black/20', 'bg-black/30', 'bg-black/40', 'bg-black/50',
        'bg-white/10', 'bg-white/20', 'bg-white/30', 'bg-white/40', 'bg-white/50',
        'bg-white/60', 'bg-white/70', 'bg-white/80', 'bg-white/90',
        'text-white/80', 'text-white/90', 'text-white/60', 'text-white/50',
        'text-black/80', 'text-black/60', 'text-black/50', 'text-black/40',
        'text-white', 'text-black',
        'border-white/10', 'border-white/20', 'border-white/30', 'border-white/50',
        'border-black/10', 'border-black/20', 'border-black/30',
        'gap-1', 'gap-2', 'gap-3', 'gap-4', 'gap-6',
        'p-1', 'p-2', 'p-3', 'p-4', 'p-5', 'p-6', 'p-8',
        'px-1', 'px-2', 'px-3', 'px-4', 'px-5', 'px-6', 'px-8',
        'py-1', 'py-2', 'py-3', 'py-4', 'py-5', 'py-6',
        'm-1', 'm-2', 'm-3', 'm-4',
        'mx-1', 'mx-2', 'mx-3', 'mx-4', 'mx-auto',
        'my-1', 'my-2', 'my-3', 'my-4',
        'rounded', 'rounded-lg', 'rounded-xl', 'rounded-2xl', 'rounded-3xl', 'rounded-full',
        'shadow-sm', 'shadow-md', 'shadow-lg', 'shadow-xl', 'shadow-2xl', 'shadow',
        'drop-shadow-sm', 'drop-shadow-md', 'drop-shadow-lg', 'drop-shadow',
        'backdrop-blur-sm', 'backdrop-blur', 'backdrop-blur-md', 'backdrop-blur-lg',
        'opacity-0', 'opacity-30', 'opacity-50', 'opacity-60', 'opacity-70', 'opacity-80', 'opacity-90',
        'z-10', 'z-20', 'z-30', 'z-40', 'z-50', 'z-100',
        'overflow-hidden', 'overflow-auto', 'overflow-y-auto', 'overflow-x-hidden',
        'cursor-pointer', 'cursor-grab', 'cursor-not-allowed',
        'flex', 'inline-flex', 'grid', 'inline-block', 'block', 'hidden',
        'flex-col', 'flex-row', 'flex-wrap', 'flex-1',
        'items-center', 'items-start', 'items-end', 'items-stretch',
        'justify-center', 'justify-start', 'justify-end', 'justify-between', 'justify-around',
        'font-thin', 'font-extralight', 'font-light', 'font-normal', 'font-medium', 'font-semibold', 'font-bold',
        'text-xs', 'text-sm', 'text-base', 'text-lg', 'text-xl', 'text-2xl', 'text-3xl', 'text-4xl', 'text-5xl',
        'uppercase', 'lowercase', 'capitalize',
        'tracking-tight', 'tracking-tighter', 'tracking-wide', 'tracking-widest',
        'leading-none', 'leading-tight', 'leading-snug', 'leading-normal', 'leading-relaxed',
        'aspect-square', 'aspect-[1/1]', 'aspect-[4/3]', 'aspect-[3/4]', 'aspect-[16/9]',
        'absolute', 'relative', 'fixed', 'sticky',
        'top-0', 'right-0', 'bottom-0', 'left-0',
        'inset-0', 'inset-x-0', 'inset-y-0',
        'col-span-1', 'col-span-2', 'col-span-3', 'col-span-4',
        'group', 'group-active\\:scale-90', 'group-active\\:scale-95',
        'transition', 'transition-all', 'transition-colors', 'transition-transform', 'transition-opacity',
        'duration-200', 'duration-300', 'duration-500',
        'ease-in', 'ease-out', 'ease-in-out',
        'animate-spin', 'animate-pulse', 'animate-bounce', 'animate-ping', 'animate-fade-in',
    ],
    plugins: [],
}
